common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home_page',views.home,name='hom'),
    path('admin_login',views.a_login,name='a_login'),
    path('student_login',views.s_login,name='s_login'),
    path('teacher_login',views.t_login,name='t_login')    
]

school/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('common.urls')),
    path('student/',include('student.urls')),
    path('s_admin/',include('school_admin.urls')),
    path('teacher/',include('teacher.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

school_admin/urls.py
from django.urls import path
from . import views

app_name = 'school_admin'

urlpatterns = [
  path('admin_home_page',views.a_home,name='hom'),
  path('add_teacher',views.add_tr,name='add_tr'),
  path('view_teacher',views.view_tr,name='view_tr'),
  path('view_student',views.view_st,name='view_st'),
  path('change_password',views.chg_pwd,name='chg_pwd')
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
  path('home_page',views.s_home,name='hom'),
  path('profile',views.prof,name='prof'),
  path('change_password',views.chg_pwd,name='chg_pwd')
]

teacher/urls.py
from django.urls import path
from . import views

app_name = 'teacher'

urlpatterns = [
  path('home_page',views.t_home,name='hom'),
  path('profile',views.prof,name='prof'),
  path('add_student',views.add_st,name='add_st'),
  path('view_student',views.view_st,name='view_st'),
  path('change_password',views.chg_pwd,name='chg_pwd')
]

common/models.py
from django.db import models

# Create your models here.

school_admin/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    teacher_name = models.CharField(max_length = 25)   # varchar(25)
    teacher_email = models.CharField(max_length = 30)
    qualification = models.CharField(max_length = 100)
    exp = models.IntegerField()
    teacher_dob = models.CharField(max_length = 100)
    teacher_phone = models.BigIntegerField()    
    teacher_profile_picture = models.ImageField(upload_to = 'teacher/')
    teacher_password = models.CharField(max_length = 20, default = "")
class AdminLogin(models.Model):
    admin_id = models.CharField(max_length = 25)   # varchar(25)
    admin_pwd = models.CharField(max_length = 30)
  

student/models.py
from django.db import models

# Create your models here.
class StudentLogin(models.Model):
    s_id = models.CharField(max_length = 25)   # varchar(25)
    s_pwd = models.CharField(max_length = 30)

teacher/models.py
from django.db import models

# Create your models here.
class TeacherLogin(models.Model):
    teacher_email = models.CharField(max_length = 30)   # varchar(25)
    teacher_password = models.CharField(max_length = 20)

common/views.py
from django.shortcuts import render,redirect
from school_admin. models import AdminLogin, Teacher
from student. models import StudentLogin
from teacher. models import TeacherLogin

# Create your views here.
def home(request):
    return render(request,'common/home.html')

def a_login(request):
    if request.method == 'POST':
        a_username = request.POST['admin_username']
        a_password = request.POST['admin_password']

        try:
            a_login = AdminLogin.objects.get(admin_id = a_username, admin_pwd = a_password)   
            return redirect('school_admin:hom')    
        except:
            msg = 'incorrect user name and password' 
            return render(request,'common/a_login.html',{'invalid_data':msg})  

    return render(request,'common/a_login.html')

def s_login(request):
    if request.method == 'POST':
        s_username = request.POST['s_user']
        s_password = request.POST['s_password']

        try:
            t_login = StudentLogin.objects.get(s_id = s_username, s_pwd = s_password)   
            return redirect('student:hom')    
        except:
            msg = 'incorrect user name and password' 
            return render(request,'common/s_login.html',{'invalid_data':msg}) 
    return render(request,'common/s_login.html')

def t_login(request):
    if request.method == 'POST':
        t_username = request.POST['teacher_email']
        t_password = request.POST['teacher_password']

        try:
            t_login = Teacher.objects.get(teacher_email = t_username, teacher_password = t_password)   
            request.session['teacher_id'] = t_login.id 
            return redirect('teacher:hom')    
        except:
            msg = 'incorrect user name and password' 
            return render(request,'common/t_login.html',{'invalid_data':msg})  

    return render(request,'common/t_login.html')

school_admin/views.py
from django.shortcuts import render
from . models import Teacher

# Create your views here.
def a_home(request):
    return render(request,'school_admin/a_home.html')

def add_tr(request):
    if request.method == 'POST':
        t_name = request.POST['teacher_name']
        t_email = request.POST['teacher_email']
        t_qualification = request.POST['qualification']
        t_dob = request.POST['birthdaytime']
        t_phone = request.POST['teacher_phone']
        t_exp = request.POST['experience']
        t_photo = request.FILES['tr_photo']        
        teacher = Teacher(teacher_name = t_name, teacher_email = t_email, qualification = t_qualification, 
        teacher_dob = t_dob, teacher_phone = t_phone, exp = t_exp, teacher_profile_picture = t_photo  )
        
        teacher.save()
    return render(request,'school_admin/add_teacher.html')

def view_st(request):
    return render(request,'school_admin/view_student.html')

def view_tr(request):
    return render(request,'school_admin/view_teachers.html')

def chg_pwd(request):
    return render(request,'school_admin/change_password.html')

student/views.py
from django.shortcuts import render

# Create your views here.
def s_home(request):
    return render(request,'student/s_home.html')

def prof(request):
    return render(request,'student/profile.html')

def chg_pwd(request):
    return render(request,'student/change_password.html')

teacher/views.py
from django.shortcuts import render

# Create your views here.
def t_home(request):
    return render(request,'teacher/t_home.html')

def prof(request):
    return render(request,'teacher/profile.html')

def view_st(request):
    return render(request,'teacher/view_student.html')

def add_st(request):
    return render(request,'teacher/add_student.html')

def chg_pwd(request):
    return render(request,'teacher/change_password.html')

common/templates/common/a_login.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login form</title>
    <link rel="stylesheet" href="{% static 'css/a_login.css' %}">
</head>
<body>

    <div id="container">
       
    <form method="POST" id="form">
        {% csrf_token %}
        <p>Login</p>
        <label for="user">Username</label><br>
        <input type="text" id="user" name="admin_username" required><br>
        <label for="password">Password</label><br>
        <input type="password" id="password" name="admin_password"><br><br>
        <label for="remember" class="remember"> &ensp;&ensp; Remember me &ensp;&ensp; </label>
        <input type="checkbox" id="remember" name="Remember">
     <a href="{% url 'school_admin:hom' %}">   <button type="submit">Login</button> </a>
     {{invalid_data}}
    </form>
    <div id="error"></div>
    </div>
    <script src="{% static 'css/login.js' %}"></script>

</body>
</html>

common/templates/common/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
        .main {
            display: grid;
            height: 600px;
            grid-template-columns: auto auto auto auto auto;
            grid-template-rows: auto auto auto;
            grid-gap: 50px;
            text-align: center;
            justify-content: center;
            padding-top: 50px;
        }

        .student {
            grid-area: 2/2/3/3;
        }

        .admin {
            grid-area: 2/3/3/4;
        }

        .teacher {
            grid-area: 2/4/3/5;
        }

        .student,
        .admin,
        .teacher {
            height: 150px;
            width: 250px;
            border: 1px solid black;
            font-size: x-large;
            font-family: Georgia, 'Times New Roman', Times, serif;
            padding-top: 25px;
            border-radius: 50px;
            background-color: black;
            color: white;
        }
        .main a{
            text-decoration: none;
            color: aliceblue;
        }
        
    </style>
</head>

<body>

    <div class="container-fluid main">
        <div class="student"><a href="{% url 'a_login' %}">
                <h2>ADMIN</h2>
            </a></div>
        <div class="admin"><a href="{% url 's_login' %}">
            <h2>STUDENT</h2></a>
        </div>
        <div class="teacher"><a href="{% url 't_login' %}">
            <h2>TEACHER</h2></a>
        </div>
    </div>

</body>

</html>

common/templates/common/s_login.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login form</title>
    <link rel="stylesheet" href="{% static 'css/s_login.css' %}">
</head>

<body>

    <div id="conteiner">
        <form method="POST" id="form">
            {% csrf_token %}
            <p>Login</p>
            <label for="user">Username</label><br>
            <input type="text" id="user" name="s_user" required><br>
            <label for="password">Password</label><br>
            <input type="password" id="password" name="s_password"><br><br>
            <label for="remember" class="remember"> &ensp;&ensp; Remember me &ensp;&ensp; </label>
            <input type="checkbox" id="remember" name="Remember">
            <a href="{% url 'student:hom' %}"> <button type="submit">Login</button> </a>
            {{invalid_data}}
        </form>
        <div id="error"></div>
    </div>
    <script src="{% static 'css/login.js' %}"></script>

</body>

</html>

common/templates/common/t_login.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login form</title>
    <link rel="stylesheet" href="{% static 'css/t_login.css' %}">
</head>
<body>

    <div id="conteiner">
    <form method="POST" id="form">
        {% csrf_token %}
        <p>Login</p>
        <label for="user">Username</label><br>
        <input type="text" id="user" name="teacher_user" required><br>
        <label for="password">Password</label><br>
        <input type="password" id="password" name="teacher_pwd"><br><br>
        <label for="remember" class="remember"> &ensp;&ensp; Remember me &ensp;&ensp; </label>
        <input type="checkbox" id="remember" name="Remember">
          <button type="submit">Login</button>   
        {{invalid_data}}
    </form>
    <div id="error"></div>
    </div>
    <script src="{% static 'css/login.js' %}"></script>

</body>
</html>

school_admin/templates/school_admin/a_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/adm_home.css' %}">
</head>

<body>

    <div class="container-fluid main">
        <div class="hm"><a href="{% url 'school_admin:hom' %}">
                <h2>HOME</h2>
            </a>
        </div>
        <div class="add_tr"><a href="{% url 'school_admin:add_tr' %}">
                <h2>ADD TEACHERS</h2>
            </a>
        </div>
        <div class="view_st"><a href="{% url 'school_admin:view_st' %}">
                <h2>VIEW STUDENT</h2>
            </a>
        </div>
        <div class="view_tr"><a href="{% url 'school_admin:view_tr' %}">
                <h2>VIEW TEACHERS</h2>
            </a>
        </div>
        <div class="chg_pwd"><a href="{% url 'school_admin:chg_pwd' %}">
                <h2>CHANGE PASSWORD</h2>
            </a>
        </div>
    </div>

</body>

</html>

school_admin/templates/school_admin/add_teacher.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/add_tr.css' %}">

</head>

<body>
    
    <div class="container">
        <div class="title">Add Teacher</div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- enctype ---to include image in form -->
            <!-- csrf_attack -->
            <div class="user__details">
                <div class="input__box">
                    <label for="" class="details">Name</label>
                    <input type="text" placeholder="Enter your Name" name="teacher_name" required>
                </div>
                <div class="input__box">
                    <label for="" class="details">Email</label>
                    <input type="email" placeholder="Enter Email" name="teacher_email" required>
                </div>

                <div class="input__box">
                    <label for="" class="details">Address</label>
                    <textarea class="form-control mt-3" id="" rows="7">
                    </textarea>
                </div>

                <div class="input__box">
                    <label for="" class="details">Qualification</label> <br>
                    <select class="form-select mt-3 form-control" name="qualification" required>
                        <option selected disabled value="">Select</option>
                        <option value="MSc,BEd">MSc,BEd</option>
                        <option value="MSc">MSc</option>
                        <option value="MSc,NET">MSc,NET</option>
                    </select>
                </div>

                <div class="input__box">

                    <label class="details" for="gender">Gender: </label>

                    <input type="radio" name="gender" id="male" required>
                    <label class="details" for="male">Male</label>

                    <input type="radio" name="gender" id="female" required>
                    <label class="details" for="female">Female</label>
                </div>

                <div class="input__box">
                    <label for="birthdaytime" class="details">DOB</label>
                    <input type="datetime-local" id="birthdaytime" name="birthdaytime">
                </div>

                <div class="input__box">
                    <label for="" class="details">Phone Number</label>
                    <input type="number" placeholder="Enter Phone Number" name="teacher_phone" required>
                </div>
                <div class="input__box">
                    <label for="" class="details">Experience</label>
                    <input type="text" placeholder="Enter Experoence in years" name="experience" required>
                </div>
                <div class="input__box">
                    <label for="" class="details">Password</label>
                    <input type="password" name="teacher_password" required>
                </div>

                <div class="input__box">
                    <label for="" class="details">Upload Photo</label>
                    <input type="file" id="st_img" name="tr_photo">
                </div>
            </div>

            <div class="button">
                <input type="submit" value="Add Teacher">
            </div>

        </form>
    </div>

</body>

</html>

school_admin/templates/school_admin/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        body {
            background: url("http://myminispot.com/images/prox.png");
            background-size: cover;
        }

        #container {
            position: absolute;
            background: #fff;
            height: 400px;
            width: 800px;
            top: 50%;
            left: 50%;
            margin-left: -400px;
            margin-top: -175px;
            text-align: center;

            box-shadow: 0px 30px 150px;
            -webkit-box-shadow: 0px 30px 150px;
            -moz-box-shadow: 0px 30px 150px;

            border-radius: 15px;
            -webkit-border-radius: 15px;
            -moz-border-radius: 15px;
        }

        #header {
            background-color: #04609D;
            font-family: 'Francois One', sans-serif;
            height: 25px;
            width: 800px;
            position: absolute;
            top: 0;
            color: white;
            margin-top: -2px;

            border-radius: 15px 15px 0px 0px;
            -webkit-border-radius: 15px 15px 0px 0px;
            -moz-border-radius: 15px 15px 0px 0px;
        }

        #footer.incorrect {
            background-color: #04609D;
            font-family: 'Francois One', sans-serif;
            height: 25px;
            width: 800px;
            position: absolute;
            bottom: 0;
            color: white;
            margin-bottom: -2px;

            border-radius: 0px 0px 15px 15px;
            -webkit-border-radius: 0px 0px 15px 15px;
            -moz-border-radius: 0px 0px 15px 15px;
        }

        #form {
            height: 180px;
            position: absolute;
            top: 25%;
            margin-top: -50px;
            width: 75%;
            left: 50%;
            margin-left: -37.5%;
            align-content: center;        
        }

        input {
            width: 70%;
            margin: 0;
            border: 0;
            border: 1px solid;
            outline: none;
            height: 50px;
            font-size: 20px;
            padding-left: 10px;
        }

        #btn1 {
            width: 30%;
            border-radius: 15px;
            background-color: #04609D;
            color: #fff;
        }

        #btn1:hover{
            background-color: blue;
            color: rgb(161, 166, 167);
        }

        input#passOne,
        input#passTwo,
        input#passOld {
            border: 1px solid;
            border-radius: 15px;
            -webkit-border-radius: 15px;
            -moz-border-radius: 15px;
        }
    </style>

</head>

<body>

    <section class="section mb-5 mt-5">
        <div class="container ">
            <div class="row justify-content-center">
                <div class="col-lg-11 text-center">
                    <div id="container">
                        <div id="header"></div>
                        <div id="form">
                            <form>
                                <!-- required -->
                                <input type="password" placeholder="Old Password" id="passOld"> <br><br>

                                <input type="password" placeholder="New Password" id="passOne"> <br><br>

                                <input type="password" placeholder="Confirm Password" id="passTwo"> <br><br><br>
                                <div class="pass-sub">
                                    <a href="">

                                        <input type="button" value="Submit" id="btn1" class="btn btn-primary"> </a>
                                </div>
                            </form>
                        </div>
                        <div id="footer" class="incorrect"></div>
                    </div>
                </div>
            </div>
        </div> <br><br><br>
        </div>
    </section>


    <script>
        $(document).ready(function () {
            var passOne = $("#passOne").val();
            var passTwo = $("#passTwo").val();

            $("#footerText").html("Fields don't match");

            var checkAndChange = function () {
                if (passOne.length < 1) {
                    if ($("#footer").hasClass("correct")) {
                        $("#footer").removeClass("correct").addClass("incorrect");
                        $("#footerText").html("They don't match");
                    } else {
                        $("#footerText").html("They don't match");
                    }
                }
                else if ($("#footer").hasClass("incorrect")) {
                    if (passOne == passTwo) {
                        $("#footer").removeClass("incorrect").addClass("correct");
                        $("#footerText").html("Continue");
                    }
                }
                else {
                    if (passOne != passTwo) {
                        $("#footer").removeClass("correct").addClass("incorrect");
                        $("#footerText").html("They don't match");
                    }
                }
            }



            $("input").keyup(function () {
                var newPassOne = $("#passOne").val();
                var newPassTwo = $("#passTwo").val();

                passOne = newPassOne;
                passTwo = newPassTwo;

                checkAndChange();
            });
        });
    </script>

</body>

</html>

school_admin/templates/school_admin/view_student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/adm_home.css' %}"> -->
    <style>
        h1 {
            padding-top: 50px;
            text-align: center;
            font-weight: bold;
        }

        .main {
            padding-top: 50px;
            width: 1200px;
        }
    </style>
</head>

<body>

    <h1> View Student </h1>

    <div class="container-fluid main">
        <div class="row">
            <div class="col-10">

                <table class="table table-primary table-striped">
                    <tr>
                        <th>Sl. No.</th>
                        <th>Photo</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>DOB</th>
                        <th> Phone No</th>
                        <th>Place</th>
                        <th>Class Teacher</th>
                        <th>Parent Name</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>

                </table>

            </div>
        </div>

    </div>

</body>

</html>

school_admin/templates/school_admin/view_teachers.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/adm_home.css' %}"> -->
    <style>
        h1{
            padding-top: 50px;
            text-align: center;
            font-weight: bold;
        }
        .main {
            padding-top: 50px;
            width: 1200px;
        }
    </style>
</head>

<body>

    <h1> View Teachers </h1>

    <div class="container-fluid main">
        <div class="row">
            <div class="col-10">

                <table class="table table-primary table-striped">
                    <tr>
                        <th>Sl. No.</th>
                        <th>Photo</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Qualification</th>
                        <th>Gender</th>
                        <th>DOB</th>
                        <th>Experience</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>

                </table>

            </div>
        </div>


    </div>

</body>

</html>

student/templates/student/s_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
        body{
    background-image: url('/static/images/bg.png');
}
        .main {
            display: grid;
            height: 700px;
            grid-template-columns: auto auto auto auto auto;
            grid-template-rows: auto auto auto;
            grid-gap: 50px;
            text-align: center;
            justify-content: center;
            padding-top: 50px;
        }


        .student {
            grid-area: 2/2/3/3;
        }

        .admin {
            grid-area: 2/3/3/4;
        }

        .teacher {
            grid-area: 2/4/3/5;
        }

        .student,
        .admin,
        .teacher {
            height: 150px;
            width: 250px;
            border: 1px solid black;
            font-size: x-large;
            font-family: Georgia, 'Times New Roman', Times, serif;
            padding-top: 10px;
            border-radius: 50px;
            background-color: rgb(103, 215, 195);
            color: rgb(50, 7, 7);
        }
    </style>
</head>

<body>

    <div class="container-fluid main">
        <div class="student"><a href="{% url 'student:hom' %}">
                <h2>HOME</h2>
            </a></div>
        <div class="admin"><a href="{% url 'student:prof' %}">
            <h2>PROFILE</h2></a>
        </div>
        <div class="teacher"><a href="{% url 'student:chg_pwd' %}">
            <h2>CHANGE PASSWORD</h2></a>
        </div>
    </div>

</body>

</html>

teacher/templates/teacher/t_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/t_home.css' %}">
</head>

<body>

    <div class="container-fluid main">
        <div class="hm"><a href="{% url 'teacher:hom' %}">
                <h2>HOME</h2>
            </a>
        </div>
        <div class="prof"><a href="{% url 'teacher:prof' %}">
                <h2>PROFILE</h2>
            </a>
        </div>
        <div class="add_st"><a href="{% url 'teacher:add_st' %}">
                <h2>ADD STUDENT</h2>
            </a>
        </div>
        <div class="view_st"><a href="{% url 'teacher:view_st' %}">
                <h2>VIEW STUDENT</h2>
            </a>
        </div>
        <div class="chg_pwd"><a href="{% url 'teacher:chg_pwd' %}">
                <h2>CHANGE PASSWORD</h2>
            </a>
        </div>
    </div>

</body>

</html>